apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersec-platform
  labels:
    app: cybersec-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cybersec-platform
  template:
    metadata:
      labels:
        app: cybersec-platform
    spec:
      containers:
      - name: cybersec-platform
        image: cybersec-platform:latest
        ports:
        - containerPort: 3000
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: cybersec-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: cybersec-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
---
apiVersion: v1
kind: Service
metadata:
  name: cybersec-platform-service
spec:
  selector:
    app: cybersec-platform
  ports:
  - name: web
    port: 80
    targetPort: 3000
  - name: api
    port: 8000
    targetPort: 8000
  type: LoadBalancer
